language: node_js

node_js : 
    - "v4.2.1"
    - "v5"


addons:
    postgresql: "9.4"


before_script:
  - psql -f test/sql/createdb.sql -U postgres
  - psql -f test/sql/db.sql -U postgres


sudo: false
